[project]
name="mcmc_bayes"
version="0.0.1"
requires-python = ">=3.12"
dependencies = [
    "dataclasses>=0.8",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "pathlib>=1.0.1",
    "scikit-learn>=1.8.0",
]
